#!/bin/bash
#
# @author Zeus Intuivo <zeus@intuivo.com>
#
#
sudo service nginx stop
sudo /etc/init.d/pumacontrol.sh stop
sudo /etc/init.d/pumacontrol.sh stop
sudo /etc/init.d/pumacontrol.sh start &
sudo /etc/init.d/pumacontrol.sh status
sudo service nginx restart
